lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, friend_detail, friend_list, delete_friend, friend_list_json

urlpatterns = [
        url(r'^$', index, name='index'),
        url(r'^add-friend/$', add_friend, name='add-friend'),
        url(r'^validate-npm/$', validate_npm, name='validate-npm'),
        url(r'^friend-list/$', friend_list, name='friend-list'),
        url(r'^friend-detail/$', friend_detail, name='friend-detail'),
        url(r'^delete-friend/$', delete_friend, name='delete-friend'),
        url(r'^get-friend-list/$', friend_list_json, name='get-friend-list')
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10

from lab_login.custom_auth import auth_login, auth_logout

urlpatterns = [
    # authentication using CSUI account
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

    # admin page
    url(r'^admin/', admin.site.urls),

    # lab pages
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
	url(r'^lab-3/', include(lab_3,namespace='lab-3')),
	url(r'^lab-4/', include(lab_4, namespace='lab-4')),
	url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
    url(r'^favicon.ico', RedirectView.as_view(url="/static/favicon.ico", permanent="True"), name='index'),
	url(r'^$', RedirectView.as_view(url="/lab-10/", permanent="True"), name='index')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_7/models.py
from django.db import models

class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250)
    added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers

from .models import Friend
from .api_csui_helper.csui_helper import get_mahasiswa_list, get_detail_mhs_by_npm

from lab_login.custom_auth import check_login
import os
import json

response = {}

def index(request):
    response = {}
    dummy_response = check_login(request, False, response)
    if dummy_response: # user need to authenticate, redirect to login
        return render(request, dummy_response, response)
    else:
        # Page halaman menampilkan list mahasiswa yang ada
        # TODO berikan akses token dari backend dengan menggunakaan helper yang ada
        if request.GET.get("page") != None and request.GET.get("from") != None:
            api_response = get_mahasiswa_list(request.session['access_token'], page=request.GET.get("page",1))
            return HttpResponse(json.dumps(api_response[0]))

        else:
            api_response = get_mahasiswa_list(request.session['access_token'], page=request.GET.get("page",1))
            friend_list = list(Friend.objects.all())[-50:]
            response.update({"mahasiswa_list": api_response[0], "friend_list": friend_list,
                        "page": request.GET.get("page",1), "friend_count": Friend.objects.count(),
                        "mhs_count": api_response[1]})
            html = 'lab_7/lab_7.html'
            return render(request, html, response)

def friend_list(request):
    response['friend_list'] = Friend.objects.all()
    response['friend_count'] = Friend.objects.count()
    response['page'] = request.GET.get("page",1)
    response['per'] = request.GET.get("per",10)

    html = 'lab_7/daftar_teman.html'
    html = check_login(request, html, response)
    return render(request, html, response)

def friend_detail(request):
    dummy_response = check_login(request, False, response)
    if dummy_response: return render(request, dummy_response, response)
    elif request.method == 'GET':
        npm = request.GET.get("npm",0)
        api_response = get_detail_mhs_by_npm(request.session['access_token'], npm)
        friends = Friend.objects.filter(npm=npm)

        if len(friends) == 0: response['friend'] = False
        else: response['friend'] = friends[0]

        response['npm'] = npm
        response['alamat_mhs'] = api_response.get("alamat_mhs","-")
        response['kd_pos_mhs'] = api_response.get("kd_pos_mhs","-")
        response['kota_lahir'] = api_response.get("kota_lahir","-")
        response['tgl_lahir'] = api_response.get("tgl_lahir","-")
        try:
            response['kd_org'] = api_response["program"][0].get("kd_org","--.--.--.--")
            response['nm_org'] = api_response["program"][0].get("nm_org","-")
            response['nm_prg'] = api_response["program"][0].get("nm_prg","undefined")
            response['angkatan'] = api_response["program"][0].get("angkatan","-")
        except KeyError:
            response['kd_org'] = "-"
            response['nm_org'] = "-"
            response['nm_prg'] = "-"
            response['angkatan'] = "-"

        html = 'lab_7/detil_teman.html'
        return render(request, html, response)

def friend_list_json(request):
    if request.method == 'GET':
        friend_list = list(Friend.objects.all())
        start = int(request.GET['start'])
        end = int(request.GET['end'])

        end = end if end <= len(friend_list) else len(friend_list)
        result = list()
        for i in range(start, end):
            result.append(model_to_dict(friend_list[i]))

        http_response = HttpResponse(json.dumps(result))
        http_response = check_login(request, http_response, response)

        if type(http_response) == HttpResponse: return http_response
        else: return render(request, http_response, response)

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        friend = Friend(friend_name=name, npm=npm)
        friend.save()
        data = model_to_dict(friend)

        http_response = HttpResponse(data)
        http_response = check_login(request, http_response, response)

        if type(http_response) == HttpResponse: return http_response
        else: return render(request, http_response, response)

def delete_friend(request):
    dummy_response = check_login(request, False, response)
    if dummy_response: # user needs to authenticate
        return render(request, dummy_response, response)
    elif request.method == 'GET':
        try:
            friend_id = int(request.GET["friend_id"])
            obj = Friend.objects.get(id=friend_id)
            obj.delete()
            return JsonResponse({"result":True})
        except:
            return JsonResponse({"result":False})

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
        'is_taken': find_friend(npm) #lakukan pengecekan apakah Friend dgn npm tsb sudah ada
    }

    http_response = JsonResponse(data)
    http_response = check_login(request, http_response, response)

    if type(http_response) == JsonResponse: return http_response
    else: return render(request, http_response, response)

def find_friend(npm):
    try:
        Friend.objects.get(npm=npm)
        return True
    except Friend.MultipleObjectsReturned:
        return True
    except Friend.DoesNotExist:
        return False

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data_dict = struct[0]["fields"]
    data_dict.update({"id":obj.id})

    data = json.dumps(data_dict)
    return data

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}
{% load staticfiles %}
{% block content %}
    <section name="friend-list" id="friend-list-section">
        <div class="container">
            <h2 style="float:left">Teman dari Fasilkom</h2>
            <div class="pagination" style="float:right">
                <a id="to-prev">&laquo;</a>
                <a id="counter"></a>
                <a id="items-per-page">
                    <select>
                        <option value=10>10</option>
                        <option value=25>25</option>
                        <option value=50>50</option>
                        <option value=100>100</option>
                    </select>
                </a>
                <a id="to-next">&raquo;</a>
            </div>
            <br style="clear:both;" />
            <div id="friend-list" class="list-group"></div>
        </div>
    </section>
{% endblock %}
{% block scripts_page %}
    <script>
        var currentPage = {{page}};
        var currentCount = {{per}};
        var friendCount = {{friend_count}};
        var pageCount = Math.ceil(friendCount/currentCount);

        var loadPage = function(page) {
            $("#friend-list").empty();
            currentPage = page;
            loadFriend();
        };

        var loadFriend = function () {
            // lengkapi pemanggilan ajax berikut untuk mengambil daftar teman yang ada di database
            $.ajax({
                method: "GET",
                url: '{% url "lab-7:get-friend-list" %}', //URL untuk mendapatkan list teman
                data: {'start': (currentPage-1)*currentCount, 'end': currentPage*currentCount},
                success: function (response) {
                    //tampilkan list teman ke halaman
                    //hint : gunakan fungsi jquery append()
                    friendList = JSON.parse(response);
                    history.pushState("", "", '{% url "lab-7:friend-list" %}?page='+currentPage+'&per='+currentCount);
                    $("#counter").html(currentPage+" of "+pageCount);

                    if (friendList.length === 0) {
                        //tampilkan pesan error
                        html = '<div class="alert alert-danger text-center">' +
                                '<strong>Oops!</strong> Tidak ada teman</div>';
                        $("#friend-list").append(html);
                        $("#to-"+currentPage).addClass("active");
                    }
                    else {
                        for (i=0; i<friendList.length; i++) {
                            curr = JSON.parse(friendList[i]);
                            id = curr.id;
                            name = curr.friend_name;
                            npm = curr.npm;
                            date = curr.added_at;

                            html = '<span class="list-group-item clearfix" id="' + id +
                                '"><a href=\'{% url "lab-7:friend-detail" %}?npm=' + npm + '\'>' +
                                name + ' (' + npm + ') [added at: ' + date + ']' +
                                '</a><span class="pull-right"><button class="btn btn-xs btn-default"' +
                                'id="del-' + id + '" onClick="deleteFriend('+ id +')">' +
                                'Hapus' + '</button></span></span>';
                            $("#friend-list").append(html);
                        }
                    }
                },
                error: function(error){
                    //tampilkan pesan error
                    html = '<div class="alert alert-danger text-center">' +
                        '<strong>Oops!</strong> Ada kesalahan pada server.</div>';
                    $("#friend-list").append(html);
                }
            });
        };

        var loadFriendOneAfterPage = function () {
            var position = (currentPage)*currentCount;

            // lengkapi pemanggilan ajax berikut untuk mengambil daftar teman yang ada di database
            $.ajax({
                method: "GET",
                url: '{% url "lab-7:get-friend-list" %}', //URL untuk mendapatkan list teman
                data: {start: position, end: position+1},
                success: function (response) {
                    //tampilkan teman setelahnya
                    friendList = JSON.parse(response);
                    if (friendList.length !== 0) {
                        friend = JSON.parse(friendList[0]);
                        id = friend.id;
                        name = friend.friend_name;
                        npm = friend.npm;
                        date = friend.added_at;

                        html = '<span class="list-group-item clearfix" id="' + id +
                            '"><a href=\'{% url "lab-7:friend-detail" %}?npm=' + npm + '\'>' +
                            name + ' (' + npm + ') [added at: ' + date + ']' +
                            '</a><span class="pull-right"><button class="btn btn-xs btn-default"' +
                            'id="del-' + id + '" onClick="deleteFriend('+ id +')">' +
                            'Hapus' + '</button></span></span>';
                        $("#friend-list").append(html);
                    }
                    else {
                        itemCount = $.trim($("#friend-list").html()).length;
                        if (!itemCount && currentPage > 1) {
                            currentPage--;
                            loadFriend();
                        }
                        else if (!itemCount) {
                            //tampilkan pesan error
                            html = '<div class="alert alert-danger text-center">' +
                                    '<strong>Oops!</strong> Tidak ada teman</div>';
                            $("#friend-list").append(html);
                        }
                    }
                }
            });
        };

        var deleteFriend = function (id) {
            $.ajax({
                method: "GET",
                url: '/lab-7/delete-friend/', //URL untuk mendapatkan list teman
                data: {friend_id:id},
                success: function(response) {
                    $("#"+id).remove();
                    $("#del-"+id).remove();
                    friendCount--;
                    pageCount = Math.ceil(currentCount/friendCount);
                    loadFriendOneAfterPage(currentPage, currentCount);
                },
                error: function(error){
                    //tampilkan pesan error
                    html = '<div class="alert alert-danger text-center">' +
                        '<strong>Oops!</strong> Penghapusan gagal</div>';
                    $("#friend-list").html(html);
                }
            });
        };

        $(document).ready(function() {
            $("#counter").html(currentPage+" of "+pageCount);
            $("#items-per-page select").val(currentCount);
            loadFriend();
        });

        $("#to-next").click(function(e) {
            if (currentPage < pageCount) loadPage(currentPage+1);
        });

        $("#to-prev").click(function(e) {
            if (currentPage > 1) loadPage(currentPage-1);
        });

        $('#items-per-page select').on('change', function() {
            currentCount = this.value;
            pageCount = Math.ceil(friendCount/currentCount);
            if (currentPage > pageCount) currentPage = pageCount;
            $("#counter").html(currentPage+" of "+pageCount);
            loadPage(currentPage);
        });
    </script>
{% endblock %}

lab_7/templates/lab_7/detil_teman.html
{% extends "lab_7/layout/base.html" %}
{% load staticfiles %}
{% block content %}
<section name="friend-list" id="friend-list-section">
    <div class="container">
        <h2>Details of {% if friend %}{{friend.friend_name}}{% else %}-{% endif %}</h2>
        <h4>{{nm_org}} angkatan {{angkatan}}</h4>
        <ul>
            <li>Curriculum Code: [{{kd_org}}] {{nm_prg}}</li>
            <li>Student Number: {{npm}}</li>
            <li>Place, Date of Birth: {{kota_lahir}}, {{tgl_lahir}}</li>
            <li>Home Address: {{alamat_mhs}}, postal code: {{kd_pos_mhs}}</li>
        </ul>
        <div id="map"></div>
    </div>
</section>
{% endblock %}
{% block scripts_page %}
<script>
    function initMap() {
        var mapOptions = {
            zoom: 12
        }
        map = new google.maps.Map(document.getElementById('map'), mapOptions);

        geocoder = new google.maps.Geocoder();
        var address = "{{alamat_mhs}}".split(/\s+/).slice(0,4).join(" ");;
        geocoder.geocode( { 'address': address}, function(results, status) {
          if (status == 'OK') {
            map.setCenter(results[0].geometry.location);
            var marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
            });
          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });
    }

      $(document).ready(initMap());
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBLM1kUUbuJ8Cxak1JJ9toBNEXBYOAvjQs&callback=initMap"></script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% load staticfiles %}
{% block content %}
    <section name="mahasiswa-list" id="mahasiswa-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2 style="float:left">Students of Fasilkom UI</h2>
                    <div class="pagination" style="float:right">
                        <a id="to-prev">&laquo;</a>
                        <a id="counter"></a>
                        <a id="to-next">&raquo;</a>
                    </div>
                    <br style="clear:both;" />
                    <div class="list-group" id="mhs-list-group">
                        {% if mahasiswa_list %}
                            {% for mahasiswa in mahasiswa_list %}
                                <a class="list-group-item clearfix">
                                    {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                    <span class="pull-right">
                                        <span class="btn btn-xs btn-default" onClick="addFriendFromAPI('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                                            Add as Friend
                                        </span>
                                    </span>
                                </a>
                            {% endfor %}
                        {% else %}
                            <div class="alert alert-danger text-center">
                                <strong>Oops!</strong> No students available.
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-4">
                    <h2> My Last 50 Friends </h2>
                    <div class="list-group" id="friend-list">
                        {% if friend_list %}
                            {% for friend in friend_list %}
                                <a class="list-group-item clearfix" href='{% url "lab-7:friend-detail" %}?npm={{friend.npm}}'>
                                    {{ friend.friend_name }} ({{ friend.npm }})
                                </a>
                            {% endfor %}
                        {% else %}
                            <div id="error-nofriend" class="alert alert-danger text-center">
                                <strong>Oops!</strong> You have no friends here.
                            </div>
                        {% endif %}
                    </div>
                    <form id="add-friend" action="#">
                        {% csrf_token %}
                        <label for="field_npm">npm</label>
                        <input id="field_npm" type="text" name="npm" class="form-control" required/>
                        <label for="field_name">name</label>
                        <input id="field_name" type="text" name="name" class="form-control" required/>
                        <button class="btn btn-xs btn-default" style="margin:10px 0" type="submit">Tambah</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block scripts_page %}
    <script>
        var friendCount = {{friend_count}};
        var pageCount = Math.ceil({{mhs_count}}/100);
        var currentPage = {{page}};

        var addFriend = function(nama, npm) {
            $.ajax({
                method: "POST",
                url: '{% url "lab-7:add-friend" %}',
                data: { name: nama, npm: npm},
                success : function (friend) {
                    $("#error-nofriend").remove();
                    if (friendCount >= 50) $("#friend-list").find(':first-child').remove();
                    friend = JSON.parse(friend);
                    html = '<a class="list-group-item clearfix"' +
                        'href=\'{% url "lab-7:friend-detail" %}?npm=' + friend.npm + '\'>' +
                        friend.friend_name + ' (' + friend.npm + ')</a>';
                    $("#friend-list").append(html);
                    friendCount++;
                },
                error : function (error) {
                    alert("Ada kesalahan pada server.")
                }
            });
        };

        var validateNpm = function(npm) {
            var isTaken = false;
            $.ajax({
                method: "POST",
                url: '{% url "lab-7:validate-npm" %}',
                data: {
                    'npm': npm
                },
                async: false,
                dataType: 'json',
                success: function (data) {
                    if (data.is_taken) alert("Mahasiswa dengan NPM seperti ini sudah ada dalam daftar teman milikmu.");
                    isTaken = data.is_taken;
                }
            });
            return isTaken;
        }

        var addFriendFromAPI = function(nama, npm) {
            validator = validateNpm(npm);
            if (!validator) addFriend(nama, npm);
        }

        var changePageMahasiswa = function(page, from) {
            $.ajax({
                method: "GET",
                url: '{% url "lab-7:index" %}',
                data: {"page":page,"from":from},
                success : function (friendList) {
                    friendList = JSON.parse(friendList);
                    $("#mhs-list-group").empty();
                    for (i=0; i<friendList.length; i++) {
                        html = '<a class="list-group-item clearfix">' +
                                friendList[i].nama + ' (' + friendList[i].npm +
                                ')<span class="pull-right"><span class="btn ' +
                                'btn-xs btn-default" onClick=\'addFriendFromAPI("' +
                                friendList[i].nama + '", "' + friendList[i].npm + '")\'>' +
                                'Tambah sebagai teman </span></span></a>';
                        $("#mhs-list-group").append(html);
                    }

                    currentPage = page;
                    history.pushState("", "", '{% url "lab-7:index" %}?page='+page);
                    $("#counter").html(currentPage+" of "+pageCount);
                }
            });
        }

        $(document).ready(function() {$("#counter").html(currentPage+" of "+pageCount)});

        $("#add-friend").on("submit", function () {
            name = $("#field_name").val()
            npm = $("#field_npm").val()
            isTaken = validateNpm(npm);

            if (!isTaken) addFriend(name, npm);
            else {
                $("#field_name").val("");
                $("#field_npm").val("");
            }
            event.preventDefault();
        });

        $("#field_npm").change(function () {
            npm = $(this).val();
            validateNpm(npm);
        });

        $("#to-next").click(function(e) {
            if (currentPage < pageCount) changePageMahasiswa(currentPage+1, "nav");
        });

        $("#to-prev").click(function(e) {
            if (currentPage > 1) changePageMahasiswa(currentPage-1, "nav");
        });
    </script>
{% endblock %}