lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_5/urls.py
from django.conf.urls import url
from .views import index, add_todo, delete_todo

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_todo', add_todo, name='add_todo'),
	url(r'^delete_todo', delete_todo, name='delete_todo'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10

from lab_login.custom_auth import auth_login, auth_logout

urlpatterns = [
    # authentication using CSUI account
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

    # admin page
    url(r'^admin/', admin.site.urls),

    # lab pages
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
	url(r'^lab-3/', include(lab_3,namespace='lab-3')),
	url(r'^lab-4/', include(lab_4, namespace='lab-4')),
	url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
    url(r'^favicon.ico', RedirectView.as_view(url="/static/favicon.ico", permanent="True"), name='index'),
	url(r'^$', RedirectView.as_view(url="/lab-10/", permanent="True"), name='index')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_5/models.py
from django.db import models

class Todo(models.Model):
	title = models.CharField(max_length=27)
	description = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

lab_5/forms.py
from django import forms

class Todo_Form(forms.Form):
	error_desc = {
		'required': 'Please fill the description with real thing.',
	}
	error_title = {
		'required': 'Please fill the title with real thing.',
	}
	title_attrs = {
		'type': 'text',
		'class': 'todo-form-input',
		'placeholder':'Insert title here...'
	}
	description_attrs = {
		'type': 'text',
		'cols': 50,
		'rows': 4,
		'class': 'todo-form-textarea',
		'placeholder':'Insert description here...'
	}

	title = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs), error_messages=error_title)
	description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs), error_messages=error_desc)

lab_5/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponseRedirect
from .forms import Todo_Form
from .models import Todo
from lab_login.custom_auth import check_login

# Create your views here.
response = {}
def index(request):
	response['author'] = "Ichlasul Affan" #TODO Implement yourname
	todo = Todo.objects.all()
	response['todo'] = todo
	html = 'lab_5/lab_5.html'
	html = check_login(request, html, response)
	response['todo_form'] = Todo_Form
	return render(request, html, response)

def add_todo(request):
	form = Todo_Form(request.POST or None)
	dummy_response = check_login(request, False, response)
	if dummy_response: return render(request, dummy_response, response)
	elif request.method == 'POST' and form.is_valid():
		response['title'] = request.POST['title']
		response['description'] = request.POST['description']
		todo = Todo(title=response['title'],description=response['description'])
		todo.save()
		messages.add_message(request, messages.SUCCESS, "Todo has been created.", extra_tags="add")
		return HttpResponseRedirect('/lab-5/')
	else:
		for x in form.errors:
			messages.add_message(request, messages.ERROR, form.errors[x], extra_tags="add")
		return HttpResponseRedirect('/lab-5/')

def delete_todo(request):
	dummy_response = check_login(request, False, response)
	if dummy_response: return render(request, dummy_response, response)
	else:
		try:
			object = Todo.objects.get(id=request.GET.get('id',''))
			object.delete()
			messages.add_message(request, messages.SUCCESS, "Todo has been deleted.", extra_tags="delete")
		except:
			messages.add_message(request, messages.ERROR, "The todo does not exist.", extra_tags="delete")
		finally: return HttpResponseRedirect('/lab-5/#my-list')

lab_5/templates/lab_5/lab_5.html
{% extends "lab_5/layout/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="content-out">
	<h1 class="main-title">TODOLIST</h1>
	<section name="input-list" id="input-list">
		<div class="container">
			<form id="form" method="POST" action="{% url 'lab-5:add_todo' %}">
				{% if messages %}
					{% for message in messages %}
						{% if message.extra_tags == "add" %}
							<div class="alert alert-{{message.level_tag}} text-center">
								<strong>{% if message.level_tag == "danger" %}Oops!{% else %}Success!{% endif %}</strong> {{message|striptags}}
							</div>
						{% endif %}
					{% endfor %}
				{% endif %}
				<h2>Input Todo</h2>
				{% csrf_token %}
				{{ todo_form }}
				<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit" onsubmit="showmessage('m-submit')">
				<br>
			</form>
		</div>
	</section>
	<section name="my-list" id="my-list">
		<div class="container">
			<h2 class="my-list-title">My List</h2>
			{% if messages %}
				{% for message in messages %}
					{% if message.extra_tags == "delete" %}
						<div class="alert alert-{{message.level_tag}} text-center">
							<strong>{% if message.level_tag == "danger" %}Oops!{% else %}Success!{% endif %}</strong> {{message|striptags}}
						</div>
					{% endif %}
				{% endfor %}
			{% endif %}
			{% if todo %}
				<div class="flex">
					{% for data in todo %}
						<div class="flex-item">
							<div class="to-do-list" id="todo-{{data.id}}">
								<div class="to-do-list-title">
									{{data.title}}
								</div>
								<div class="to-do-list-date-added">
									{{data.created_date}}
								</div>
								<a class="to-do-list-delete" href="{% url 'lab-5:delete_todo' %}?id={{data.id}}" style="z-index:-1" onclick="showmessage('m-submit')">Delete</a>
								<div class="to-do-list-description">
									{{data.description}}
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
			{% else %}
			<div class="alert alert-danger text-center">
				<strong>Oops!</strong> Nothing here. Please fill the form above.
			</div>
			{% endif %}
		</div>
	</section>
</div>
{% endblock %}