lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_8/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
        url(r'^$', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10

from lab_login.custom_auth import auth_login, auth_logout

urlpatterns = [
    # authentication using CSUI account
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

    # admin page
    url(r'^admin/', admin.site.urls),

    # lab pages
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
	url(r'^lab-3/', include(lab_3,namespace='lab-3')),
	url(r'^lab-4/', include(lab_4, namespace='lab-4')),
	url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
    url(r'^favicon.ico', RedirectView.as_view(url="/static/favicon.ico", permanent="True"), name='index'),
	url(r'^$', RedirectView.as_view(url="/lab-10/", permanent="True"), name='index')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_8/models.py
from django.db import models

# Create your models here.

lab_8/views.py
from django.shortcuts import render
from lab_login.custom_auth import check_login

# Create your views here.
response = {}
def index(request):
    html = 'lab_8/lab_8.html'
    html = check_login(request, html, response)
    return render(request, html, response)

lab_8/templates/lab_8/partials/footer.html
<p class="copyright">Made with Love by Ichlasul Affan. (c) 2017</p>

lab_8/templates/lab_8/partials/header.html
<nav class="navbar navbar-default navbar-expand-lg fixed-top navbar-dark bg-dark" id="navbar">
  <div class="container">
  <a class="navbar-brand" href="/"><b>ppw-ichlasulaffan</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item"><a class="nav-link" href="{% url 'lab-8:index' %}#">Cover</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'lab-8:index' %}#post-field">New Post</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'lab-8:index' %}#timeline">Timeline</a></li>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Other Apps <b class="caret"></b></a>
          <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdownMenuLink">
            <li><a href="{% url 'lab-1:index' %}" class="nav-dd-item nav-item nav-link">Lab 1: Sandbox</a></li>
            <li><a href="{% url 'lab-2:index' %}" class="nav-dd-item nav-item nav-link">Lab 2: Landing Page</a></li>
            <li><a href="{% url 'lab-3:index' %}" class="nav-dd-item nav-item nav-link">Lab 3: Diary</a></li>
            <li><a href="{% url 'lab-4:index' %}" class="nav-dd-item nav-item nav-link">Lab 4: Portofolio</a></li>
            <li><a href="{% url 'lab-5:index' %}" class="nav-dd-item nav-item nav-link">Lab 5: TODOLIST</a></li>
            <li><a href="{% url 'lab-6:index' %}" class="nav-dd-item nav-item nav-link">Lab 6: Chat n Calc</a></li>
            <li><a href="{% url 'lab-7:index' %}" class="nav-dd-item nav-item nav-link">Lab 7: FasilkomFriends</a></li>
            <li><a href="{% url 'lab-9:index' %}" class="nav-dd-item nav-item nav-link">Lab 9: Electron Shop</a></li>
            <li><a href="{% url 'lab-10:index' %}" class="nav-dd-item nav-item nav-link">Lab 10: Cinema</a></li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto" id="nav-log">
          <li class="nav-item"><a id="nav-user" class="nav-link">[CSUI] {{user_login}}</a></li>
        <li class="nav-item"><a id="nav-log-fb" class="nav-link" onclick="facebookLogin()">
          <img src="/static/img/glyphicons/facebook.png"> Login FB
        </a></li>
        <li class="nav-item" style='background:#800'><a id="logout" class="nav-link" href='{% url "auth_logout" %}'>Logout CSUI</a></li>
      </ul>
    </div>
  </div>
</nav>